### ISSUE TITLE
PC version .spc files differ from Vita version

### ISSUE THREAD

**Issue by SHSLYakuza** [BlackDragonHunt/Danganronpa-Tools#1]
I've compared both the .spc files which would normally contain sprites such as the ones in model/chara. However, I noticed that the PC version has a much bigger file size for each "stand_" file compared to the Vita version.
I tried using the tool, however, the dec folder comes up with empty folders, especially inside the chara-ex folder. I assume this is because of a different type of compression used?

**Comment by yukinogatari** [comment]
This is most likely the result of bad CPK extraction. The old QuickBMS cpk extraction script can't handle files this large, so it starts spitting out junk after the first ~4 GB of data. Use a program like [CriPakTools](https://github.com/esperknight/CriPakTools) to extract the file and it should work.

**Comment by SHSLYakuza** [comment]
Thanks, I'll give it a go.

**Comment by SHSLYakuza** [comment]
Alright, it seems like it still extracts empty folders, only this time I get a message after it tries to extract the spc. And I used the tool you specified to extract the cpk this time.
https://puu.sh/xJDRp/4e86306285.png

**Comment by yukinogatari** [comment]
You need to update your repo. I added support for that image format when the demo came out.

**Comment by SHSLYakuza** [comment]
Sorry, my bad, thanks a bunch, didn't realize.
